[package]
name = "libtww"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
arrayvec = { version = "0.4.7", default-features = false }

[features]
alloc = []
